### ISSUE TITLE
problem running program

### ISSUE THREAD

**Issue by neococo** [VlachosGroup/AIMSim#235]
I was able to install in a python3.9 virtual environment from the windows terminal - however, the command 'aimsim' fails because of:

ImportError: cannot import name 'ToolTip' from 'idlelib.tooltip'

I'm not an expert - I assume this is something about versions of python where they changed the upper vs lowercase of certain commands or packages. 

Any ideas?

**Comment by himaghna** [comment]
Hi @neococo  could you upload the complete stack trace? That would help us identify where the crash is happening. Thanks!

**Comment by neococo** [comment]
Sorry I'm a novice at this,  but I think this is what you're asking for. I tried it again today from a different computer.

I installed Python 3.8 for windows x64
I made a virtual environment from Windows Powershell
>python -m venv aimsim
>cd aimsim
>Scripts\Activate
>pip install aimsim
Collecting aimsim…
# I omitted all the downloads/installing
# Aimsim install was successful it seems. 

(aimsim) PS C:\Users\User1\aimsim> aimsim
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User1\aimsim\Scripts\aimsim.exe\__main__.py", line 7, in <module>
  File "c:\users\User1\aimsim\lib\site-packages\aimsim\__main__.py", line 14, in start_AIMSim
    from interfaces.UI import AIMSim_ui_main
  File "c:\users\User1\aimsim\lib\site-packages\interfaces\UI\AIMSim_ui_main.py", line 26, in <module>
    from idlelib.tooltip import ToolTip
ImportError: cannot import name 'ToolTip' from 'idlelib.tooltip' (C:\Users\User1\AppData\Local\Programs\Python\Python38\lib\idlelib\tooltip.py)
(aimsim) PS C:\Users\User1\aimsim>

**Comment by himaghna** [comment]
Thanks! This helps. @JacksonBurns  this seems to be originating from the UI module. Could you take a look?

**Comment by JacksonBurns** [comment]
Ultimately resolved this by changing the tooltip to use an external package which is still being actively maintained. This was a long overdue change anyway. Merging now.

**Comment by neococo** [comment]
Maybe you can let me know if this is a program that is able to be run from the windows command line while inside a python virtual environment? I reinstalled successfully, but get a different error this time upon running 'aimsim'

(aimsim) PS C:\Users\User1> aimsim
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User1\aimsim\Scripts\aimsim.exe\__main__.py", line 7, in <module>
  File "c:\users\User1\aimsim\lib\site-packages\aimsim\__main__.py", line 16, in start_AIMSim
    sys.exit(AIMSim_ui_main.main())
  File "c:\users\User1\aimsim\lib\site-packages\interfaces\UI\AIMSim_ui_main.py", line 605, in main
    app = AIMSimUiApp()
  File "c:\users\User1\aimsim\lib\site-packages\interfaces\UI\AIMSim_ui_main.py", line 64, in __init__
    self.titleLabel = ctk.CTkLabel(
  File "c:\users\User1\aimsim\lib\site-packages\customtkinter\windows\widgets\ctk_label.py", line 90, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "c:\users\User1\aimsim\lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['text_font'] are not supported arguments. Look at the documentation for supported arguments.
(aimsim) PS C:\Users\User1>

**Comment by himaghna** [comment]
Opened a new bug for this Issue #237
