### ISSUE TITLE
UI ValueError issue

### ISSUE THREAD

**Issue by himaghna** [VlachosGroup/AIMSim#237]
Maybe you can let me know if this is a program that is able to be run from the windows command line while inside a python virtual environment? I reinstalled successfully, but get a different error this time upon running 'aimsim'

(aimsim) PS C:\Users\User1> aimsim
Traceback (most recent call last):
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User1\aimsim\Scripts\aimsim.exe\__main__.py", line 7, in <module>
  File "c:\users\User1\aimsim\lib\site-packages\aimsim\__main__.py", line 16, in start_AIMSim
    sys.exit(AIMSim_ui_main.main())
  File "c:\users\User1\aimsim\lib\site-packages\interfaces\UI\AIMSim_ui_main.py", line 605, in main
    app = AIMSimUiApp()
  File "c:\users\User1\aimsim\lib\site-packages\interfaces\UI\AIMSim_ui_main.py", line 64, in __init__
    self.titleLabel = ctk.CTkLabel(
  File "c:\users\User1\aimsim\lib\site-packages\customtkinter\windows\widgets\ctk_label.py", line 90, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "c:\users\User1\aimsim\lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['text_font'] are not supported arguments. Look at the documentation for supported arguments.
(aimsim) PS C:\Users\User1>

_Originally posted by @neococo in https://github.com/VlachosGroup/AIMSim/issues/235#issuecomment-1382909528_

**Comment by JacksonBurns** [comment]
Turns out there was a breaking API change in `customtkinter` - when this was originally written, one could set the font using [`text_font`](https://github.com/TomSchimansky/CustomTkinter/wiki/CTkLabel/d99f5584a2722cfb937470325b91a94ae5e63a0a) but nowadays it is just [`font`](https://github.com/TomSchimansky/CustomTkinter/wiki/CTkLabel).

I will open a PR and update all of the calls.

**Comment by neococo** [comment]
does this mean it should work now? I tried to go run pip install aimsim and now it won't even install. Do I need to wait a day for things to update? 

Thanks for your help!

**Comment by JacksonBurns** [comment]
Hi @neococo I just updated the package on PyPI, so now it should work properly when installed. For ease of use, it would be best to delete the virtual environment you currently have and make a new one for this install. You may also have to open the UI with `python -m aimsim` rather than just `aimsim`.
Feel free to re-open if issues persist!

**Comment by neococo** [comment]
it worked!! the UI opened up - was able to just run 'aimsim' from the python virtual enviroment inside windows powershell. thanks for helping get it running! I'll test it out.
