### ISSUE TITLE
Use SimSIMD for Acclerated Similarity Comparisons

### ISSUE THREAD

**Issue by JacksonBurns** [VlachosGroup/AIMSim#266]
SimSIMD (https://github.com/ashvardanian/SimSIMD) implements a number of our similarity criteria, but like _way_ faster. We should change some of our similarity implementations to use those, rather than the numpy/scipy equivalents.

**Comment by Alejo1982** [comment]
Dear @JacksonBurns and all,
I am very happy to start using this software.
I have already created the corresponding conda enviroment.
I installed AIMSim with this command: "`conda install -c conda-forge aimsim`"
But, when I want to use it via typing: "`aimsim`".
I get:

```
/home/david/psi4conda/envs/AimSim/lib/python3.14/site-packages/interfaces/UI/AIMSim_ui_main.py:21: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Traceback (most recent call last):
  File "/home/david/psi4conda/envs/AimSim/bin/aimsim", line 10, in <module>
    sys.exit(start_AIMSim())
             ~~~~~~~~~~~~^^
  File "/home/david/psi4conda/envs/AimSim/lib/python3.14/site-packages/aimsim/__main__.py", line 14, in start_AIMSim
    from interfaces.UI import AIMSim_ui_main
  File "/home/david/psi4conda/envs/AimSim/lib/python3.14/site-packages/interfaces/UI/AIMSim_ui_main.py", line 24, in <module>
    from .libraries import customtkinter as ctk
ImportError: cannot import name 'customtkinter' from 'interfaces.UI.libraries' (unknown location)
```


How can I solve this small issue?
I cannot wait to use all the capability of this software!!!
Best regards,
David
